select 
    W_ZIP AS ZIP, 
    W_WAREHOUSE_NAME AS WAREHOUSE_NAME, 
    W_STREET_NAME AS STREET_NAME, 
    W_STATE AS STATE, 
    W_CITY AS CITY, 
    W_COUNTY AS COUNTY, 
    W_STREET_TYPE AS STREET_TYPE, 
    W_WAREHOUSE_SQ_FT AS WAREHOUSE_SQ_FT, 
    W_SUITE_NUMBER AS SUITE_NUMBER, 
    W_STREET_NUMBER AS STREET_NUMBER, 
    W_COUNTRY AS COUNTRY, 
    W_WAREHOUSE_SK AS WAREHOUSE_SK, 
    W_GMT_OFFSET AS GMT_OFFSET, 
    W_WAREHOUSE_ID AS WAREHOUSE_ID,  
    _AIRBYTE_NORMALIZED_AT AS DATETIMESTAMP
from {{source('tpcds','warehouse')}}