select 
    SM_SHIP_MODE_SK as SHIP_MODE_SK, 
    SM_TYPE AS SHIP_MODE_TYPE, 
    SM_CODE AS SHIP_MODE_CODE, 
    SM_CARRIER AS CARRIER, 
    SM_CONTRACT, 
    SM_SHIP_MODE_ID AS SHIP_MODE_ID, 
    _AIRBYTE_NORMALIZED_AT AS DATETIMESTAMP
from {{source('tpcds','ship_mode')}}